/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3.vista;

import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import practica3.controlador.*;
import practica3.modelo.*;

/**
 *
 * @author nacho
 */
public class JPanelListaFecha extends javax.swing.JPanel {

    private Lista lista;
    private Lista listaAux;
    /**
     * Creates new form JPanelListaFecha
     */
    public JPanelListaFecha() {
        initComponents();
    }
    
    public void actulizarLista(Lista lista)
    {
        this.lista = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFecha = new javax.swing.JTextField();
        ButtonSiguiente = new javax.swing.JButton();
        jTextMinutosPartidos = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ButtonAnterior = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jLabelMinutosPartidos = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextSueldo = new javax.swing.JTextField();
        ButtonDia = new javax.swing.JButton();
        ButtonMes = new javax.swing.JButton();
        ButtonAño = new javax.swing.JButton();
        jTextFiltra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        ButtonSiguiente.setText("Siguiente");
        ButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSiguienteActionPerformed(evt);
            }
        });

        jTextNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextNombreInputMethodTextChanged(evt);
            }
        });
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tipo:");

        ButtonAnterior.setText("Anterior");
        ButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnteriorActionPerformed(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFecha.setText("Fecha alta:");

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Lista de Jugadores");

        jLabelSueldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSueldo.setText("Sueldo:");

        jLabelMinutosPartidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMinutosPartidos.setText("Partidos/Minutos:");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        ButtonDia.setText("Día");
        ButtonDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiaActionPerformed(evt);
            }
        });

        ButtonMes.setText("Mes");
        ButtonMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMesActionPerformed(evt);
            }
        });

        ButtonAño.setText("Año");
        ButtonAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAñoActionPerformed(evt);
            }
        });

        jTextFiltra.setToolTipText("");

        jLabel2.setText("Filtrar por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMinutosPartidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextMinutosPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelSueldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonAnterior)
                            .addComponent(jLabel2))
                        .addGap(279, 279, 279)
                        .addComponent(ButtonSiguiente)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTitulo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFiltra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonDia)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonMes)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonAño)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFecha))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSueldo))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMinutosPartidos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextMinutosPartidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFiltra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDia)
                    .addComponent(ButtonMes)
                    .addComponent(ButtonAño))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAnterior)
                    .addComponent(ButtonSiguiente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void iniBotones()
    {
        ButtonAnterior.setEnabled(false);
        
        if(lista.vacia())
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "AVISO. No hay ningún jugador registrado.");
        }
        else
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Selecciona antes el metodo de filtrado.");
        }
    }
    
    private void ButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSiguienteActionPerformed
        // TODO add your handling code here:
        listaAux.siguiente();
        System.out.println("Pasa al siguiente");
        
        setJTextField(listaAux);
        
        if(listaAux.getActual() == listaAux.ultimo())
            ButtonSiguiente.setEnabled(false);
        ButtonAnterior.setEnabled(true);

    }//GEN-LAST:event_ButtonSiguienteActionPerformed

    private void jTextNombreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextNombreInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreInputMethodTextChanged

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void ButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnteriorActionPerformed
        // TODO add your handling code here:
        listaAux.retrocede();
        System.out.println("Pasa al anterior");
        
        setJTextField(listaAux);
        
        if(listaAux.getActual() == listaAux.primero())
            ButtonAnterior.setEnabled(false);
        ButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_ButtonAnteriorActionPerformed

    private int meterDato()
    {
        int dato;
        
        dato = Integer.parseInt(jTextFiltra.getText());
        
        return dato;
    }
    private void ButtonDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiaActionPerformed
        // TODO add your handling code here:
        
        int dia = Integer.parseInt(jTextFiltra.getText());
        int diaCogido;
        
        this.listaAux = new Lista();
        
        lista.principio();
        
        Nodo aux = null;
        
        while(lista.getActual() != null)
        {
            
            String aux2 = lista.extraerObjeto().toString();
            String [] array = aux2.split("\\|");
            
            String cadenaAux = array[1];
            
            GregorianCalendar fechaAux = Terminal.parseDate(array[1]);
            
            diaCogido = Integer.parseInt(
                Terminal
                        .parseDate(fechaAux)
                        .substring(0,2));
            
            aux = lista.getActual();
                
            if (aux != null && dia == diaCogido)
                listaAux.añadirNodo(new Nodo(aux));
            
            lista.siguiente();
        }
        
        //listaAux = lista.filtrarListaDia(meterDato());
        setJTextField(listaAux);
        
        ButtonAnterior.setEnabled(false);
        
        if(listaAux.vacia())
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "AVISO. No hay ningún jugador registrado en ese dia.");
        }
        else if(listaAux.primero().getSgt() == null)
            ButtonSiguiente.setEnabled(false);
        else
            ButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_ButtonDiaActionPerformed

    private void ButtonMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMesActionPerformed
        // TODO add your handling code here:
        listaAux = lista.filtrarListaMes(meterDato());
        setJTextField(listaAux);
        
        ButtonAnterior.setEnabled(false);
        
        if(listaAux.vacia())
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "AVISO. No hay ningún jugador registrado en ese mes.");
        }
        else if(listaAux.primero().getSgt() == null)
            ButtonSiguiente.setEnabled(false);
        else
            ButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_ButtonMesActionPerformed

    private void ButtonAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAñoActionPerformed
        // TODO add your handling code here:
        listaAux = lista.filtrarListaAño(meterDato());
        setJTextField(listaAux);
        
        ButtonAnterior.setEnabled(false);
        
        if(listaAux.vacia())
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "AVISO. No hay ningún jugador registrado en ese año.");
        }
        else if(listaAux.primero().getSgt() == null)
            ButtonSiguiente.setEnabled(false);
        else
            ButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_ButtonAñoActionPerformed

    public void setJTextField(Lista lista)
    {
        String aux = lista.extraerObjeto().toString();
        String [] array = aux.split("\\|");
        jTextNombre.setText(array[0]);
        jTextFecha.setText(array[1]);
        jTextSueldo.setText(array[2]);
        jTextMinutosPartidos.setText(array[4]);
        jTextField1.setText(array[5]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnterior;
    private javax.swing.JButton ButtonAño;
    private javax.swing.JButton ButtonDia;
    private javax.swing.JButton ButtonMes;
    private javax.swing.JButton ButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMinutosPartidos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFiltra;
    private javax.swing.JTextField jTextMinutosPartidos;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextSueldo;
    // End of variables declaration//GEN-END:variables
}
