/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3.vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import practica3.controlador.*;
import practica3.modelo.*;

/**
 *
 * @author nacho
 */
public class JPanelListaDato extends javax.swing.JPanel {
    
    private Lista lista;
    private Lista listaAux;
    /**
     * Creates new form JPanelLista
     */
    public JPanelListaDato() 
    {        
        initComponents();
    }
    
    public void actulizarLista(Lista lista)
    {
        this.lista = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFecha = new javax.swing.JTextField();
        ButtonSiguiente = new javax.swing.JButton();
        jTextMinutosPartidos = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextPosicion = new javax.swing.JTextField();
        ButtonAnterior = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jLabelMinutosPartidos = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPosicion = new javax.swing.JLabel();
        jTextSueldo = new javax.swing.JTextField();
        ButtonTitular = new javax.swing.JButton();
        ButtonSuplente = new javax.swing.JButton();

        ButtonSiguiente.setText("Siguiente");
        ButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSiguienteActionPerformed(evt);
            }
        });

        jTextNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextNombreInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tipo:");

        ButtonAnterior.setText("Anterior");
        ButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnteriorActionPerformed(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFecha.setText("Fecha alta:");

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Lista de Jugadores");

        jLabelSueldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSueldo.setText("Sueldo:");

        jLabelMinutosPartidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMinutosPartidos.setText("Partidos/Minutos:");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelPosicion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPosicion.setText("Posición:");

        ButtonTitular.setText("Titulares");
        ButtonTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTitularActionPerformed(evt);
            }
        });

        ButtonSuplente.setText("Suplentes");
        ButtonSuplente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSuplenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPosicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelMinutosPartidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextMinutosPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonSiguiente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFecha)
                            .addComponent(jLabelSueldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombre)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jTextSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addComponent(jTextFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTitulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ButtonTitular)
                        .addGap(54, 54, 54)
                        .addComponent(ButtonSuplente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSueldo)
                    .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinutosPartidos)
                    .addComponent(jTextMinutosPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPosicion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPosicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTitular)
                    .addComponent(ButtonSuplente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSiguiente)
                    .addComponent(ButtonAnterior))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void iniBotones()
    {
        ButtonAnterior.setEnabled(false);
        
        if(lista.vacia())
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "AVISO. No hay ningún jugador registrado.");
        }
        else
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Selecciona antes el metodo de filtrado.");
        }
        
    }
    
    private void ButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSiguienteActionPerformed
        // TODO add your handling code here:
        listaAux.siguiente();
        System.out.println("Pasa al siguiente");
        
        setJTextField(listaAux);
        
        if(listaAux.getActual() == listaAux.ultimo())
            ButtonSiguiente.setEnabled(false);
        ButtonAnterior.setEnabled(true);
    }//GEN-LAST:event_ButtonSiguienteActionPerformed

    private void jTextNombreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextNombreInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreInputMethodTextChanged

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void ButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnteriorActionPerformed
        // TODO add your handling code here:
        listaAux.retrocede();
        System.out.println("Pasa al anterior");
        
        setJTextField(listaAux);
        
        if(listaAux.getActual() == listaAux.primero())
            ButtonAnterior.setEnabled(false);
        ButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_ButtonAnteriorActionPerformed

    private void ButtonTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTitularActionPerformed
        // TODO add your handling code here:
        listaAux = lista.filtrarTipo("titular");
        setJTextField(listaAux);
        
        ButtonAnterior.setEnabled(false);
        
        if(listaAux.vacia())
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "AVISO. No hay ningún jugador registrado de ese tipo.");
        }
        else if(listaAux.primero().getSgt() == null)
            ButtonSiguiente.setEnabled(false);
        else
            ButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_ButtonTitularActionPerformed

    private void ButtonSuplenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSuplenteActionPerformed
        // TODO add your handling code here:
        listaAux = lista.filtrarTipo("suplente");
        setJTextField(listaAux);
        
        ButtonAnterior.setEnabled(false);
        
        if(listaAux.vacia())
        {
            ButtonSiguiente.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "AVISO. No hay ningún jugador registrado de ese tipo.");
        }
        else if(listaAux.primero().getSgt() == null)
            ButtonSiguiente.setEnabled(false);
        else
            ButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_ButtonSuplenteActionPerformed

    public void setJTextField(Lista lista)
    {
        String aux = lista.extraerObjeto().toString();
        String [] array = aux.split("\\|");
        jTextNombre.setText(array[0]);
        jTextFecha.setText(array[1]);
        jTextSueldo.setText(array[2]);
        jTextMinutosPartidos.setText(array[4]);
        jTextField1.setText(array[5]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnterior;
    private javax.swing.JButton ButtonSiguiente;
    private javax.swing.JButton ButtonSuplente;
    private javax.swing.JButton ButtonTitular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMinutosPartidos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPosicion;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextMinutosPartidos;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPosicion;
    private javax.swing.JTextField jTextSueldo;
    // End of variables declaration//GEN-END:variables
}
