/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3.vista;

import practica3.controlador.*;
/**
 *
 * @author nacho
 */
public class JPanelBusFecha extends javax.swing.JPanel {

    private Lista lista;
    private Lista listaAux;
    private JPanelListaFecha pDia;
    private JPanelListaFecha pMes;
    private JPanelListaFecha pAño;
    private int opcion;
    /**
     * Creates new form JPanelBusFecha
     */
    public JPanelBusFecha(JPanelListaFecha pDia, JPanelListaFecha pMes, JPanelListaFecha pAño) {
        initComponents();
        this.pDia = pDia;
        this.pMes = pMes;
        this.pAño = pAño;
    }
    
    public void actulizarLista(Lista lista)
    {
        this.lista = lista;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonDia = new javax.swing.JButton();
        ButtonMes = new javax.swing.JButton();
        ButtonAño = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Búsqueda de jugadores");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setText("por fecha de alta");

        ButtonDia.setText("Buscar por día");
        ButtonDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiaActionPerformed(evt);
            }
        });

        ButtonMes.setText("Buscar por mes");
        ButtonMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMesActionPerformed(evt);
            }
        });

        ButtonAño.setText("Buscar por año");
        ButtonAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAñoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Selecciona la opcion de búsqueda:");

        jLabel4.setText("Por dia:");

        jLabel5.setText("Por mes:");

        jLabel6.setText("Por año:");

        jTextField1.setToolTipText("Introduce dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonDia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonMes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonAño, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDia)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMes)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAño)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ButtonDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiaActionPerformed
        // TODO add your handling code here:
        /*System.out.println("Va a hacer lista aux");
        listaAux = lista.filtrarListaDia(Integer.parseInt(jTextField1.getText()));
        System.out.println("Llena lista aux");
        pDia.actulizarLista(listaAux); //CADA VEZ QUE SE SELECCIONA EL BOTON PARA ENTRAR EN LA LISTA, SE LE PASA LA LISTA ACTUALIZADA
        System.out.println("Mete lista aux");
        
        if(!listaAux.vacia()) //SI LA LISTA NO ESTA VACIA, MUESTRA LOS DATOS DEL PRIMERO
            pDia.setJTextField(listaAux);
        */
        this.opcion = 1;
    }//GEN-LAST:event_ButtonDiaActionPerformed

    private void ButtonMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMesActionPerformed
        // TODO add your handling code here:
        listaAux = lista.filtrarListaMes(Integer.parseInt(jTextField2.getText()));
        pDia.actulizarLista(listaAux); //CADA VEZ QUE SE SELECCIONA EL BOTON PARA ENTRAR EN LA LISTA, SE LE PASA LA LISTA ACTUALIZADA
        
        if(!listaAux.vacia()) //SI LA LISTA NO ESTA VACIA, MUESTRA LOS DATOS DEL PRIMERO
            pMes.setJTextField(listaAux);
        
        this.opcion = 2;
    }//GEN-LAST:event_ButtonMesActionPerformed

    private void ButtonAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAñoActionPerformed
        // TODO add your handling code here:
        listaAux = lista.filtrarListaAño(Integer.parseInt(jTextField3.getText()));
        pDia.actulizarLista(listaAux); //CADA VEZ QUE SE SELECCIONA EL BOTON PARA ENTRAR EN LA LISTA, SE LE PASA LA LISTA ACTUALIZADA
        
        if(!listaAux.vacia()) //SI LA LISTA NO ESTA VACIA, MUESTRA LOS DATOS DEL PRIMERO
            pAño.setJTextField(listaAux);
        
        this.opcion = 3;
    }//GEN-LAST:event_ButtonAñoActionPerformed

    public int pBusFechaOpcion()
    {        
        return this.opcion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAño;
    private javax.swing.JButton ButtonDia;
    private javax.swing.JButton ButtonMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
