/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Modelo.*;
import Controlador.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author Nacho y Jorge
 */

public class JPanelJList extends javax.swing.JPanel {

    private ArrayList <Trabajador> list = new ArrayList<Trabajador>();
    
    /**
     * Creates new form JPanelJList
     */
    
    public JPanelJList() {
        initComponents();
    }
    
    public void actualizaLista(){
        this.list=GestionJList.rellenaArray();
    }
    
    public void iniciarJList(){
        if(list.isEmpty()){//SI EL ARRAYLIST ESTÁ VACIO
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"AVISO. No hay ningun trabajador registrado.");
        }
    }
    private DefaultListModel modeloLista()
    {
        DefaultListModel <Trabajador> modelo = new DefaultListModel <Trabajador>();


        for(int i = 0; i < list.size(); i++ )
        {
            modelo.addElement(list.get(i));
        }
        return modelo;
        
    }
    
    public void rellenaJList()
    {
        jList1.setModel(modeloLista());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        BotonMostrar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Lista de trabajadores");

        jList1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        BotonMostrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonMostrar.setText("Mostrar");
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 214, Short.MAX_VALUE)
                        .addComponent(BotonMostrar)
                        .addGap(224, 224, 224))))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        String men;
        Object jlist = jList1.getSelectedValue();

        if(jList1.getSelectedIndex() != -1)
        {
            men = "El elemento seleccionado es: \n" + jlist.toString();
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, men);
        }else
        {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "ERROR. No se ha seleccionado ningún elemento.");
        }
    }//GEN-LAST:event_BotonMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
