/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;
import Controlador.*;
import Modelo.*;

/**
 *
 * @author Nacho
 */
public class JPanelLista extends javax.swing.JPanel {

    /**
     * Creates new form JPanelLista
     */
    
    private int numeroEmp;
    private Trabajador tra;
    
    public JPanelLista(int numero) {
        this.numeroEmp = numero;
        initComponents();
        rellenaLista();
        inibotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSiguiente = new javax.swing.JButton();
        jTextFieldFecha = new javax.swing.JTextField();
        jButtonAnterior = new javax.swing.JButton();
        jButtonPrimero = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jLabelSueldo = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSueldo = new javax.swing.JTextField();
        jLabelFoto = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldFoto = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSiguiente.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));
        add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        jButtonAnterior.setBackground(new java.awt.Color(0, 204, 204));
        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jButtonPrimero.setBackground(new java.awt.Color(0, 204, 204));
        jButtonPrimero.setText("Primero");
        jButtonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeroActionPerformed(evt);
            }
        });
        add(jButtonPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jButtonUltimo.setBackground(new java.awt.Color(0, 204, 204));
        jButtonUltimo.setText("Último");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });
        add(jButtonUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jLabelNombre.setText("Nombre");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jButtonModificar.setBackground(new java.awt.Color(0, 204, 204));
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jLabelSueldo.setText("Sueldo");
        add(jLabelSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabelFecha.setText("Fecha");
        add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 34, -1));
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 85, -1));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Lista de trabajadores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 50));

        jTextFieldSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSueldoActionPerformed(evt);
            }
        });
        add(jTextFieldSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 88, -1));
        add(jLabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 137, 137));

        jButtonAceptar.setBackground(new java.awt.Color(51, 255, 51));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(255, 51, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jTextFieldFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFotoActionPerformed(evt);
            }
        });
        add(jTextFieldFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        tra = GestionTrabajador.avanzar();
        setJtextField(tra);

        jButtonAnterior.setEnabled(true);
        jButtonPrimero.setEnabled(true);

        if(GestionTrabajador.esUltimo())
        {
            jButtonSiguiente.setEnabled(false);
            jButtonUltimo.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        tra = GestionTrabajador.retroceder();
        setJtextField(tra);

        jButtonSiguiente.setEnabled(true);
        jButtonUltimo.setEnabled(true);

        if(GestionTrabajador.esPrimero())
        {
            jButtonAnterior.setEnabled(false);
            jButtonPrimero.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeroActionPerformed
        // TODO add your handling code here:
        tra = GestionTrabajador.verPrimero();
        setJtextField(tra);

        jButtonSiguiente.setEnabled(true);
        jButtonUltimo.setEnabled(true);
        jButtonPrimero.setEnabled(false);
        jButtonAnterior.setEnabled(false);
    }//GEN-LAST:event_jButtonPrimeroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        tra = GestionTrabajador.verUltimo();
        setJtextField(tra);

        jButtonAnterior.setEnabled(true);
        jButtonPrimero.setEnabled(true);
        jButtonUltimo.setEnabled(false);
        jButtonSiguiente.setEnabled(false);
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        botonesModificar(0);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTextFieldSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSueldoActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        botonesModificar(1);
        
        if(jTextFieldFoto.getText() == "")
            GestionTrabajador.modificarTrabajador(jTextFieldNombre.getText(), jTextFieldSueldo.getText(), jLabelFoto.getText(), jTextFieldNumero.getText());
        else
            GestionTrabajador.modificarTrabajador(jTextFieldNombre.getText(), jTextFieldSueldo.getText(), jTextFieldFoto.getText(), jTextFieldNumero.getText());
        
        rellenaLista();
        inibotones();
        
        jButtonSiguiente.setEnabled(true);
        jButtonUltimo.setEnabled(true);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        botonesModificar(1);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFotoActionPerformed

    private void botonesModificar(int bandera)
    {
        if(bandera == 0)
        {
        jButtonAnterior.setVisible(false);
        jButtonPrimero.setVisible(false);
        jButtonSiguiente.setVisible(false);
        jButtonUltimo.setVisible(false);
        jButtonModificar.setVisible(false);
        jLabelFoto.setVisible(false);
        jButtonAceptar.setVisible(true);
        jButtonCancelar.setVisible(true);
        jTextFieldFoto.setVisible(true);
        
        jTextFieldNombre.setEditable(true);
        jTextFieldSueldo.setEditable(true);
        }else
        {
            jButtonAnterior.setVisible(true);
            jButtonPrimero.setVisible(true);
            jButtonSiguiente.setVisible(true);
            jButtonUltimo.setVisible(true);
            jButtonModificar.setVisible(true);
            jLabelFoto.setVisible(true);
            jButtonAceptar.setVisible(false);
            jButtonCancelar.setVisible(false);
            jTextFieldFoto.setVisible(false);
            
            jTextFieldNombre.setEditable(false);
            jTextFieldSueldo.setEditable(false);
            jTextFieldFecha.setEditable(false);
        }
    }
    
    private void inibotones()
    {
        jButtonAnterior.setEnabled(false);
        jButtonPrimero.setEnabled(false);
        jButtonAceptar.setVisible(false);
        jButtonCancelar.setVisible(false);
        jTextFieldFoto.setVisible(false);
        
        jTextFieldNombre.setEditable(false);
        jTextFieldSueldo.setEditable(false);
        jTextFieldFecha.setEditable(false);
        jTextFieldNumero.setEditable(false);
    }
    
    private void setJtextField(Trabajador tra)
    {
        jTextFieldNumero.setText(String.valueOf(tra.getNumero()));
        jTextFieldNombre.setText(tra.getNombre());
        jTextFieldFecha.setText(String.valueOf(tra.getFecha()));
        jTextFieldSueldo.setText(String.valueOf(tra.getSueldo()));
        ImageIcon icon = new ImageIcon("src/Fotos/"+tra.getFoto());
        jLabelFoto.setIcon(icon);
    }
    
    private void rellenaLista()
    {
        tra = GestionTrabajador.primero(numeroEmp);
        setJtextField(tra);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonPrimero;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldFoto;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldSueldo;
    // End of variables declaration//GEN-END:variables
}
