package Vista;

import Controlador.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nacho y Jorge
 */

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    private int numeroEmp; //Para guardar el numero de la empresa logeada
    
    public Principal() {
        initComponents();
        GestionConex.conectar();
        desactivaComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemPerfil = new javax.swing.JMenuItem();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemLista1a1 = new javax.swing.JMenuItem();
        jMenuItemAlta = new javax.swing.JMenuItem();
        jMenuItemJList = new javax.swing.JMenuItem();
        jMenuAcercaDe = new javax.swing.JMenu();
        jMenuNosotros = new javax.swing.JMenuItem();
        jMenuItemAplicacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Gestor empresarial");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Iniciar Sesión");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContraseña.setText("Contraseña:");

        jButton.setText("Aceptar");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jMenuUsuario.setText("Opciones");

        jMenuItemPerfil.setText("Modificar empresa");
        jMenuItemPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPerfilActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemPerfil);

        jMenuItemCerrarSesion.setText("Cerrar sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenuUsuario);

        jMenuOpciones.setText("Gestión trabajadores");
        jMenuOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpcionesActionPerformed(evt);
            }
        });

        jMenuItemLista1a1.setText("Ver trabajadores");
        jMenuItemLista1a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLista1a1ActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemLista1a1);

        jMenuItemAlta.setText("Nuevo trabajador");
        jMenuItemAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemAlta);

        jMenuItemJList.setText("Ver JList");
        jMenuItemJList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJListActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemJList);

        jMenuBar1.add(jMenuOpciones);

        jMenuAcercaDe.setText("Acerca de");
        jMenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAcercaDeActionPerformed(evt);
            }
        });

        jMenuNosotros.setText("Nosotros");
        jMenuNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNosotrosActionPerformed(evt);
            }
        });
        jMenuAcercaDe.add(jMenuNosotros);

        jMenuItemAplicacion.setText("La aplicación");
        jMenuItemAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAplicacionActionPerformed(evt);
            }
        });
        jMenuAcercaDe.add(jMenuItemAplicacion);

        jMenuBar1.add(jMenuAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContraseña)
                    .addComponent(jLabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(54, 54, 54)
                        .addComponent(jLabelContraseña)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_jButtonActionPerformed

    private void jMenuItemPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPerfilActionPerformed
        // TODO add your handling code here:
        pModEmp = new JPanelModEmp(numeroEmp);
        this.setContentPane(pModEmp);
        pack();
    }//GEN-LAST:event_jMenuItemPerfilActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        cerrarSesion();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemLista1a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLista1a1ActionPerformed
        pLista = new JPanelLista(numeroEmp);
        this.setContentPane(pLista);
        //pLista.iniBotones();
        pack();
    }//GEN-LAST:event_jMenuItemLista1a1ActionPerformed

    private void jMenuItemAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaActionPerformed
        // TODO add your handling code here:
        pAlta = new JPanelAlta(numeroEmp);
        this.setContentPane(pAlta);
        pack();
    }//GEN-LAST:event_jMenuItemAltaActionPerformed

    private void jMenuOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpcionesActionPerformed

    }//GEN-LAST:event_jMenuOpcionesActionPerformed

    private void jMenuNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNosotrosActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"App realizada por Ignacio Martínez de Carvajal Andrés.\n"
                + "y Jorge Elias Alkhoury Gaviño.");
    }//GEN-LAST:event_jMenuNosotrosActionPerformed

    private void jMenuItemAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAplicacionActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"App de gestión de trabajadores de una empresa.");
    }//GEN-LAST:event_jMenuItemAplicacionActionPerformed

    private void jMenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAcercaDeActionPerformed

    }//GEN-LAST:event_jMenuAcercaDeActionPerformed

    private void jMenuItemJListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJListActionPerformed
        // TODO add your handling code here:
        pJList = new JPanelJList();
        this.setContentPane(pJList);
        pJList.actualizaLista();
        pJList.rellenaJList();
        pJList.iniciarJList();
        pack();
    }//GEN-LAST:event_jMenuItemJListActionPerformed

    public void iniciarSesion()
    {
        String nombre = jTextFieldNombre.getText();
        String contraseña = jPasswordField1.getText();
        
        String consulta1 = "select * from EMPRESA where nomEmp = '" + nombre +"' and contraseña = " + contraseña;
        
        if(GestionConex.consultaInicial(nombre, contraseña) == true)
        {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"Inicio de sesión realizado con exito.");
            
            numeroEmp = GestionConex.sacarNumero(nombre);
            
            jMenuBar1.setVisible(true);
            jLabel2.setVisible(false);
            jLabelNombre.setVisible(false);
            jLabelContraseña.setVisible(false);
            jTextFieldNombre.setVisible(false);
            jButton.setVisible(false);
            jPasswordField1.setVisible(false);
            
            GestionTrabajador.abrir();
            GestionEmpresa.abrir();
            
        }else
        {
             JFrame frame = new JFrame();
             JOptionPane.showMessageDialog(frame,"Nombre o contraseña incorrectos.\nIntentalo de nuevo.");
             jTextFieldNombre.setText("");
             jPasswordField1.setText("");
        }
    }
    
    public void cerrarSesion()
    {
        GestionEmpresa.cerrar();
        GestionTrabajador.cerrar();
        GestionConex.cerrar();
        
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Se ha cerrado la sesión.");
    }
    
    public void desactivaComponentes()
    {
        jMenuBar1.setVisible(false);
        //jTextFieldContraseña.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private Vista.JPanelLista pLista;
    private Vista.JPanelAlta pAlta;
    private Vista.JPanelModEmp pModEmp;
    private Vista.JPanelJList pJList;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JMenu jMenuAcercaDe;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlta;
    private javax.swing.JMenuItem jMenuItemAplicacion;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemJList;
    private javax.swing.JMenuItem jMenuItemLista1a1;
    private javax.swing.JMenuItem jMenuItemPerfil;
    private javax.swing.JMenuItem jMenuNosotros;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
