/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Lista;
import Controlador.Nodo;
import Modelo.Empleado;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nacho
 */
public class PanelListaFecha extends javax.swing.JPanel {

    private Lista <Empleado> list;
    
    /**
     * Creates new form PanelListaFecha
     */
    public PanelListaFecha() {
        initComponents();
        jLabelSueldo.setVisible(false);
        jLabelMax.setVisible(false);
        jTextMax.setVisible(false);
        jTFSueldo.setVisible(false);
        jTextNumero.setVisible(false);
        jLabelNumero.setVisible(false);
        BotAvanzar.setVisible(false);
        BotRetroceder.setVisible(false);
        jTFNombre.setVisible(false);
        jLabelNombre.setVisible(false);
    }
    
    public void actualizaLista(Lista <Empleado> list){
        this.list=list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextNumero = new javax.swing.JTextField();
        jLabelFechaAlta = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jTextMax = new javax.swing.JTextField();
        BotRetroceder = new javax.swing.JButton();
        jLabelMax = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        BotAvanzar = new javax.swing.JButton();
        jLabelNumero = new javax.swing.JLabel();
        jTFSueldo = new javax.swing.JTextField();
        jButtonBorrar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        jTextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroActionPerformed(evt);
            }
        });

        jLabelFechaAlta.setText("Fecha de Alta");

        jLabelSueldo.setText("Sueldo");
        jLabelSueldo.setToolTipText("");

        BotRetroceder.setText("Retroceder");
        BotRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRetrocederActionPerformed(evt);
            }
        });

        jLabelMax.setText("Sueldo Máx:");

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Lista de empleados por fecha");

        jLabelNombre.setText("Nombre");

        BotAvanzar.setText("Avanzar");
        BotAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAvanzarActionPerformed(evt);
            }
        });

        jLabelNumero.setText("Número:");

        jButtonBorrar.setText("Borrar");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextMax, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFechaAlta)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelSueldo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFSueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBorrar)
                            .addComponent(BotRetroceder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotAvanzar)
                            .addComponent(jButtonAceptar))
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaAlta)
                    .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSueldo))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMax)
                    .addComponent(jTextMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotRetroceder)
                    .addComponent(BotAvanzar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonAceptar)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroActionPerformed

    public void iniBotones(){
        BotRetroceder.setEnabled(false);
        
        
        if(list.vacia()){
            BotAvanzar.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"AVISO. No hay ningún jugador registrado.");
        }
        else if (list.getActual().getSgt()==null)
            BotAvanzar.setEnabled(false);
        else
            BotAvanzar.setEnabled(true);
            
    }
    
    private void BotRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRetrocederActionPerformed

        list.retrocede();
        
        String fecha = jTFFecha.getText();
        
        for(Nodo <Empleado> aux = list.primero(); aux != null; aux = aux.getSgt())
        {
            
            if(aux.getDato().getFecha().equals(fecha))
            {
                System.out.println("Entra en if");
                setJTextField(list);
                break;             
            }          
        }
           
        if(list.getActual()==list.primero())
        BotRetroceder.setEnabled(false);

        BotAvanzar.setEnabled(true);
    }//GEN-LAST:event_BotRetrocederActionPerformed

    private void BotAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAvanzarActionPerformed
        list.siguiente();
        
        String fecha = jTFFecha.getText();
        
        for(Nodo <Empleado> aux = list.primero(); aux != null; aux = aux.getSgt())
        {
            System.out.println("Fecha" + aux.getDato().getFecha());
            
            if(aux.getDato().getFecha().equals(fecha))
            {
                System.out.println("Entra en if");
                setJTextField(list);
                break;             
            }          
        }
        
        if(list.getActual().getSgt()== null)
        BotAvanzar.setEnabled(false);

        BotRetroceder.setEnabled(true);
    }//GEN-LAST:event_BotAvanzarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        String fecha = jTFFecha.getText();
        int ultimo = 0; //para saber si ha llegado al ultimo
        
        for(Nodo <Empleado> aux = list.primero(); aux != null; aux = aux.getSgt())
        {
            System.out.println("Fecha" + aux.getDato().getFecha());
            
            if(aux.getDato().getFecha().equals(fecha))
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "Lista filtrada por fecha '"+ fecha + "'.");
                jButtonAceptar.setVisible(false);
                jButtonBorrar.setVisible(false);
                jLabelSueldo.setVisible(false);
                jLabelMax.setVisible(true);
                jTextMax.setVisible(true);
                jTFSueldo.setVisible(true);
                jLabelSueldo.setVisible(true);
                jTextNumero.setVisible(true);
                jLabelNumero.setVisible(true);
                BotAvanzar.setVisible(true);
                BotRetroceder.setVisible(true);
                jTFNombre.setVisible(true);
                jLabelNombre.setVisible(true);
                break;             
            }else if(aux.getSgt() == null)
            {
                ultimo = 1;
            }
                
        }
        
        if(ultimo == 1)
        {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "No hay empleados dados de alta esa fecha.");
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    public void setJTextField(Lista <Empleado> p){
        String cadena = p.extraerObjeto().toString();     
        String [] datos = cadena.split("\\|");
        jTextNumero.setText(datos[0]);
        jTFNombre.setText(datos[1]);
        jTFSueldo.setText(datos[3]);
        jTextMax.setText(datos[4]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAvanzar;
    private javax.swing.JButton BotRetroceder;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JLabel jLabelMax;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFSueldo;
    private javax.swing.JTextField jTextMax;
    private javax.swing.JTextField jTextNumero;
    // End of variables declaration//GEN-END:variables
}
