/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.*;
import Modelo.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nacho
 */
public class PanelModificar extends javax.swing.JPanel {

    private Lista <Empleado> lista;
    private Nodo <Empleado> aux;
    
    int op;
    int bandera = 0;
    
    String nombre = "", sueldoMax = "", sueldo = "", fecha = "", foto = "";
    
    /**
     * Creates new form PanelModificar
     */
    public PanelModificar() {
        initComponents();
        jButtonAceptar2.setVisible(false);
        jTextField1.setVisible(false);
        jComboBox1.setVisible(false);
    }
    
    public void actualizarLista(Lista <Empleado> lista)
    {
        this.lista = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextFecha = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButtonAceptar2 = new javax.swing.JButton();

        jLabelTitulo.setText("Modificar empleado");

        jLabelNombre.setText("Nombre:");

        jLabelFecha.setText("Fecha alta:");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar todo");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un campo:", "Nombre", "Apellido", "Fecha", "Sueldo", "Foto" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButtonAceptar2.setText("Aceptar");
        jButtonAceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBorrar)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonAceptar2))
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFecha)
                    .addComponent(jTextNombre)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonAceptar2))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificar(Nodo <Empleado> aux)
    {
    }
    
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:

        String nombre = jTextNombre.getText();
        String fecha = jTextFecha.getText();
        int ultimo = 0; //para saber si ha llegado al ultimo

        for(Nodo <Empleado> aux2 = lista.primero(); aux2 != null; aux2 = aux2.getSgt())
        {

            if(aux2.getDato().getNombre().equals(nombre) && aux2.getDato().getFecha().equals(fecha))
            {
                jTextNombre.setVisible(false);
                jTextFecha.setVisible(false);
                jLabelNombre.setVisible(false);
                jLabelFecha.setVisible(false);
                jButtonAceptar.setVisible(false);
                jButtonBorrar.setVisible(false);
                jButtonAceptar2.setVisible(true);
                jTextField1.setVisible(true);
                jComboBox1.setVisible(true);
                aux = aux2;
                break;
            }else if(aux2.getSgt() == null)
            {
                ultimo = 1;
            }

        }

        if(ultimo == 1)
        {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Los datos introducidos no son correctos.");
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        jTextNombre.setText("");
        jTextFecha.setText("");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String opcion = jComboBox1.getSelectedItem().toString();

        if(opcion.equals("Nombre"))
        {
            op = 1;
        }else if(opcion.equals("Apellido"))
        {
            op = 2;
        }else if(opcion.equals("Fecha"))
        {
            op = 3;
        }else if(opcion.equals("Sueldo"))
        {
            op = 4;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private boolean comprobarFecha(){
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        String strDate = jTextField1.getText();
       
        if (strDate.trim().equals(""))
	{
	    return false;
	}
	/* Date is not 'null' */
	else
	{
	    /*
	     * Set preferred date format,
	     * For example MM-dd-yyyy, MM.dd.yyyy,dd.MM.yyyy etc.*/
	    SimpleDateFormat sdfrmt = new SimpleDateFormat("MM/dd/yyyy");
	    sdfrmt.setLenient(false);
	    /* Create Date object
	     * parse the string into date 
             */
	    try
	    {
	        Date javaDate = sdfrmt.parse(strDate); 
	    }
	    /* Date format is invalid */
	    catch (ParseException e)
	    {
	        return false;
	    }
	    /* Return true if date format is valid */
	    return true;
	}

        
    }
    
    private boolean comprobarNumero(){
        try{
            int n = Integer.parseInt(jTextField1.getText());
            
        }catch(NumberFormatException e){
            return false;
        }
        return true;
    }
    
    private void jButtonAceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptar2ActionPerformed
        // TODO add your handling code here:
        switch(op)
        {
            case 1:
            {
                nombre = jTextField1.getText();
                //System.out.println(nombre);
                break;
            }
            case 2:
            {
                try{                   
                    if(!comprobarNumero())
                        throw new ControlException("");
                    
                    sueldoMax = jTextField1.getText();
                    bandera = 0;
                }catch(ControlException e){
                    ControlException ex = new ControlException("int");
                    jTextField1.setText("");
                    bandera = 1;
                }
            }
            case 3:
            {
                try{
                     if(!comprobarFecha())
                        throw new ControlException("");
                     
                    fecha = jTextField1.getText();
                    bandera = 0;
                }catch(ControlException e){
                    ControlException ex = new ControlException("fecha");
                    jTextField1.setText("");
                    bandera = 1;
                }
                
                break;
            }
            case 4:
            {
                try{                   
                    if(!comprobarNumero())
                        throw new ControlException("");
                    
                    sueldo = jTextField1.getText();
                    bandera = 0;
                }catch(ControlException e){
                    ControlException ex = new ControlException("int");
                    jTextField1.setText("");
                    bandera = 1;
                }
                
                break;
            }

        }
        
        if(!nombre.equals(""))
        {
            aux.getDato().setNombre(nombre);
        }
        
        if(!sueldoMax.equals(""))
        {
            aux.getDato().setSueldoMaximo(Integer.parseInt(sueldoMax));
        }
        
        if(!fecha.equals(""))
        {
            try {
                aux.getDato().setFecha(fecha);
            } catch (Exception ex) {
                Logger.getLogger(PanelModificar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(!sueldo.equals(""))
        {
            aux.getDato().setSueldo(Integer.parseInt(sueldo));
        }
        
        if(bandera == 0)
        {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"Perfil modificado");
        }
    }//GEN-LAST:event_jButtonAceptar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAceptar2;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
