package Vista;

import Controlador.*;
import Modelo.*;

/**
 *
 * @author Nacho
 */

public class Principal extends javax.swing.JFrame {

    Lista <Empleado> lista = new Lista <Empleado> ();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        creaObjeto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemAlta = new javax.swing.JMenuItem();
        jMenuItemBaja = new javax.swing.JMenuItem();
        jMenuModificar = new javax.swing.JMenuItem();
        jMenuListados = new javax.swing.JMenu();
        jMenuItemNormal = new javax.swing.JMenuItem();
        jMenuItemFecha = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLICACIÓN DE GESTIÓN DE EMPLEADOS");

        jMenuOpciones.setText("Opciones");

        jMenuItemAlta.setText("Dar de alta");
        jMenuItemAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemAlta);

        jMenuItemBaja.setText("Dar de baja");
        jMenuItemBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBajaActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemBaja);

        jMenuModificar.setText("Modificar");
        jMenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuModificar);

        jMenuBar1.add(jMenuOpciones);

        jMenuListados.setText("Listados");

        jMenuItemNormal.setText("Normal");
        jMenuItemNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNormalActionPerformed(evt);
            }
        });
        jMenuListados.add(jMenuItemNormal);

        jMenuItemFecha.setText("Por fecha");
        jMenuItemFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFechaActionPerformed(evt);
            }
        });
        jMenuListados.add(jMenuItemFecha);

        jMenuBar1.add(jMenuListados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBajaActionPerformed
        // TODO add your handling code here:
        this.setContentPane(pBaja);
        pBaja.actualizarLista(lista);
        pack();
    }//GEN-LAST:event_jMenuItemBajaActionPerformed

    private void jMenuItemAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaActionPerformed
        // TODO add your handling code here:
        this.setContentPane(pAlta);
        pAlta.actualizarLista(lista);
        pack();
    }//GEN-LAST:event_jMenuItemAltaActionPerformed

    private void jMenuItemNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNormalActionPerformed
        // TODO add your handling code here:
        this.setContentPane(pLista);
        pLista.actualizaLista(lista);
        pLista.iniBotones();
        
        if(!lista.vacia()) //SI LA LISTA NO ESTA VACIA, MUESTRA LOS DATOS DEL PRIMERO
            pLista.setJTextField(lista);
        
        pack();
    }//GEN-LAST:event_jMenuItemNormalActionPerformed

    private void jMenuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarActionPerformed
        // TODO add your handling code here:
        this.setContentPane(pModificar);
        pModificar.actualizarLista(lista);
        pack();
    }//GEN-LAST:event_jMenuModificarActionPerformed

    private void jMenuItemFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFechaActionPerformed
        // TODO add your handling code here:
        this.setContentPane(pListaFecha);
        pListaFecha.actualizaLista(lista);
        pListaFecha.iniBotones();
        
        pack();
    }//GEN-LAST:event_jMenuItemFechaActionPerformed

    private void creaObjeto(){ //CREAR OBJETOS INICIALES EN LA LISTA
        
        Empleado emp1 = new Empleado("Pepe", 1500, 2000, "10/10/2010");
        lista.crearNodo(emp1, emp1.getNumero());
        Empleado emp2 = new Empleado("Rocio", 2000, 2500, "19/09/2022");
        lista.crearNodo(emp2, emp2.getNumero());
        Empleado emp3 = new Empleado("Lola", (float) 900.75, 1000, "10/10/2010");
        lista.crearNodo(emp3, emp3.getNumero());
        Empleado emp4 = new Empleado("Juan", (float) 1800.5, 1900, "19/09/2022");
        lista.crearNodo(emp4, emp4.getNumero());   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    //DECLARACIÓN DE PANELES
    private PanelListar pLista = new PanelListar();
    private PanelAlta pAlta = new PanelAlta();
    private PanelBaja pBaja = new PanelBaja();
    private PanelListaFecha pListaFecha = new PanelListaFecha();
    private PanelModificar pModificar = new PanelModificar();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlta;
    private javax.swing.JMenuItem jMenuItemBaja;
    private javax.swing.JMenuItem jMenuItemFecha;
    private javax.swing.JMenuItem jMenuItemNormal;
    private javax.swing.JMenu jMenuListados;
    private javax.swing.JMenuItem jMenuModificar;
    private javax.swing.JMenu jMenuOpciones;
    // End of variables declaration//GEN-END:variables
}
