package vista;

import modelo.*;
import Controlador.*;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author alumno
 */
public class Aplicacion4 extends javax.swing.JFrame {

    Lista <Empleado> lista = new Lista <Empleado> ();
    ArrayList<Empleado> miarray = new ArrayList<Empleado>();
    
    public Aplicacion4() {
        initComponents();
        creaObjeto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAltas = new javax.swing.JMenu();
        jMenuItemAnalista = new javax.swing.JMenuItem();
        jMenuItemProgramador = new javax.swing.JMenuItem();
        jMenuFicheros = new javax.swing.JMenu();
        jMenuItemCargar = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenu();
        jMenuItemJList = new javax.swing.JMenuItem();
        jMenuItemLista = new javax.swing.JMenuItem();
        jMenuItemOrdenar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuAltas.setText("Altas");

        jMenuItemAnalista.setText("Analista");
        jMenuItemAnalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnalistaActionPerformed(evt);
            }
        });
        jMenuAltas.add(jMenuItemAnalista);

        jMenuItemProgramador.setText("Programador");
        jMenuItemProgramador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProgramadorActionPerformed(evt);
            }
        });
        jMenuAltas.add(jMenuItemProgramador);

        jMenuBar1.add(jMenuAltas);

        jMenuFicheros.setText("Fichero");

        jMenuItemCargar.setText("Cargar");
        jMenuItemCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarActionPerformed(evt);
            }
        });
        jMenuFicheros.add(jMenuItemCargar);

        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuFicheros.add(jMenuItemGuardar);

        jMenuBar1.add(jMenuFicheros);

        jMenuListar.setText("Listar");

        jMenuItemJList.setText("Lista Completa");
        jMenuItemJList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJListActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemJList);

        jMenuItemLista.setText("Lista 1 a 1");
        jMenuItemLista.setToolTipText("");
        jMenuItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemLista);

        jMenuItemOrdenar.setText("Ordenar Lista");
        jMenuItemOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrdenarActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemOrdenar);

        jMenuBar1.add(jMenuListar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaActionPerformed
        // TODO add your handling code here:
        pLista = new PanelListar();
        
        this.setContentPane(pLista);
        pLista.actualizaLista(lista); //CADA VEZ QUE SE SELECCIONA EL BOTON PARA ENTRAR EN LA LISTA, SE LE PASA LA LISTA ACTUALIZADA
        
        pLista.iniBotones();
        
        if(!lista.vacia()) //SI LA LISTA NO ESTA VACIA, MUESTRA LOS DATOS DEL PRIMERO
            pLista.setJTextField(lista);
        
        pack();
    }//GEN-LAST:event_jMenuItemListaActionPerformed

    private void jMenuItemAnalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnalistaActionPerformed
        // TODO add your handling code here:
        this.setContentPane(AltaAnalista);
        AltaAnalista.actualizarLista(lista);
        AltaAnalista.actualizarArray(miarray);
        pack(); 
    }//GEN-LAST:event_jMenuItemAnalistaActionPerformed

    private void jMenuItemProgramadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProgramadorActionPerformed
        // TODO add your handling code here:
        this.setContentPane(AltaProgramador);
        AltaProgramador.actualizarLista(lista);
        AltaProgramador.actualizarArray(miarray);
        pack(); 
    }//GEN-LAST:event_jMenuItemProgramadorActionPerformed

    
    private void jMenuItemOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrdenarActionPerformed
        // TODO add your handling code here:
        
        for(int i = 0; i< 25000; i++)
        {
            int f = (int) Math.floor(Math.random()*(25000-1000+1)+1000);
            Analista ana = new Analista(f,"Pepa",1500f,"11/11/1111",0.5f,"buena");
            lista.crearNodo(ana, ana.getNumero());
            miarray.add(ana);
        }
        
        long inicio = System.currentTimeMillis();
             
        lista.ordenarLista();
      
        long fin = System.currentTimeMillis();
         
        double tiempo = (double) ((fin - inicio));

        long inicio2 = System.currentTimeMillis();
        Collections.sort(miarray, new ElementComparator());
        for (int i = 0; i < miarray.size(); i++) {
         }
        long fin2 = System.currentTimeMillis();
         
        double tiempo2 = (double) ((fin2 - inicio2));
         
        
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame, "La lista ha tardado " + tiempo + " milisegundos.\nEl arrayList ha tardado " + tiempo2 + " milisegundos.");
    }//GEN-LAST:event_jMenuItemOrdenarActionPerformed

    private void jMenuItemJListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJListActionPerformed
        // TODO add your handling code here:
        this.setContentPane(pJLista);
        pJLista.actualizaLista(lista);
        //System.out.println("Lista actulizada");
        pJLista.rellenaJList();
        //System.out.println("Lista rellenada");
        pJLista.iniciarJList();
        pack();
    }//GEN-LAST:event_jMenuItemJListActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        // TODO add your handling code here:
        ControlFicheros fichero = new ControlFicheros();
        fichero.creaFichero(lista);
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarActionPerformed
        // TODO add your handling code here:
        ControlFicheros fichero = new ControlFicheros();
        lista = fichero.leeFichero();
    }//GEN-LAST:event_jMenuItemCargarActionPerformed

    
    
    public void creaObjeto(){
        Analista ana1 = new Analista(1, "Pepe", 1000f, "23/10/2020", 0.5f, "Buena gente");
        lista.crearNodo(ana1, ana1.getNumero());
        miarray.add(ana1);
        Programador pro1 = new Programador(2, "Juan", 1000f, "23/09/2021", 0.5f, 5);
        lista.crearNodo(pro1, pro1.getNumero());
        miarray.add(pro1);
        Analista ana2 = new Analista(3, "Jose", 1000f, "23/10/2020", 0.5f, "Buena gente");
        lista.crearNodo(ana2, ana2.getNumero());
        miarray.add(ana2);
        Programador pro2 = new Programador(4, "Paco", 1000f, "23/09/2021", 0.5f, 5);
        lista.crearNodo(pro2, pro2.getNumero());
        miarray.add(pro2);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch(Exception e){
            System.out.println(e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion4().setVisible(true);
            }
        });
    }
    
    private vista.PanelListar pLista = new PanelListar();
    private vista.PanelAltasAnalista AltaAnalista = new PanelAltasAnalista();
    private vista.PanelAltasProgramador AltaProgramador = new PanelAltasProgramador();
    private vista.PanelJLista pJLista = new PanelJLista();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAltas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFicheros;
    private javax.swing.JMenuItem jMenuItemAnalista;
    private javax.swing.JMenuItem jMenuItemCargar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemJList;
    private javax.swing.JMenuItem jMenuItemLista;
    private javax.swing.JMenuItem jMenuItemOrdenar;
    private javax.swing.JMenuItem jMenuItemProgramador;
    private javax.swing.JMenu jMenuListar;
    // End of variables declaration//GEN-END:variables
}
