/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import Controlador.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author alumno
 */
public class PanelListar extends javax.swing.JPanel {

    
    private Lista <Empleado> list;

    
    public PanelListar() {
        initComponents();
        
    }

    public void actualizaLista(Lista <Empleado> list){
        this.list=list;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        BotAvanzar = new javax.swing.JButton();
        jTFSueldo = new javax.swing.JTextField();
        jLabelSueldo = new javax.swing.JLabel();
        jLabelFechaAlta = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        BotRetroceder = new javax.swing.JButton();
        jLabelPagas = new javax.swing.JLabel();
        jLabelAtributos = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextTipo = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jTextPagas = new javax.swing.JTextField();
        jTextAtributo = new javax.swing.JTextField();
        BotCalcular = new javax.swing.JButton();

        setToolTipText("");

        jLabelNombre.setText("Nombre");

        BotAvanzar.setText("Avanzar");
        BotAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAvanzarActionPerformed(evt);
            }
        });

        jLabelSueldo.setText("Sueldo");
        jLabelSueldo.setToolTipText("");

        jLabelFechaAlta.setText("Fecha de Alta");

        BotRetroceder.setText("Retroceder");
        BotRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRetrocederActionPerformed(evt);
            }
        });

        jLabelPagas.setText("Sueldo Extra/Plus Anual:");

        jLabelAtributos.setText("Proyectos/Conducta:");

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Lista1 a 1");

        jLabelTipo.setText("Tipo:");

        jTextTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTipoActionPerformed(evt);
            }
        });

        jLabelNumero.setText("Número:");

        jTextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroActionPerformed(evt);
            }
        });

        BotCalcular.setText("Calcular");
        BotCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(BotRetroceder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotAvanzar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelAtributos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelPagas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextPagas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaAlta)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelSueldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotCalcular)
                    .addComponent(jLabelTitulo))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaAlta)
                    .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSueldo))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPagas)
                    .addComponent(jTextPagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAtributos)
                    .addComponent(jTextAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotRetroceder)
                    .addComponent(BotAvanzar)
                    .addComponent(BotCalcular))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void iniBotones(){
        BotRetroceder.setEnabled(false);
        
        
        if(list.vacia()){
            BotAvanzar.setEnabled(false);
            BotCalcular.setEnabled(false);
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"AVISO. No hay ningún jugador registrado.");
        }
        else if (list.getActual().getSgt()==null)
            BotAvanzar.setEnabled(false);
        else
            BotAvanzar.setEnabled(true);
            
    }
    
    private void BotAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAvanzarActionPerformed
        list.siguiente();
        setJTextField(list);
        if(list.getActual().getSgt()== null)
            BotAvanzar.setEnabled(false);
        
        BotRetroceder.setEnabled(true);
        
    }//GEN-LAST:event_BotAvanzarActionPerformed

    private void BotRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRetrocederActionPerformed

        list.retrocede();
        setJTextField(list);
        if(list.getActual()==list.primero())
            BotRetroceder.setEnabled(false);
        
        BotAvanzar.setEnabled(true);
        
    }//GEN-LAST:event_BotRetrocederActionPerformed

    private void jTextTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTipoActionPerformed

    private void jTextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroActionPerformed

    private void BotCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCalcularActionPerformed
        // TODO add your handling code here:
        if(jTextTipo.getText().equals("Analista")){
            //System.out.println("Entra en analista");
            Analista ana = (Analista)list.extraerObjeto();
            
            if(ana.cumpleAño())
            {
                float Sueldo,Resultado;
                Sueldo = ana.getSueldo();
                
                Resultado = Sueldo + Sueldo * ana.getPlusAnual();
                
                jTFSueldo.setText(Float.toString(Resultado));
            }else
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "Error. El Empleado no cumple el requisito de 1 año mínimo");
            }
        }else
        {
            Programador pro = (Programador)list.extraerObjeto();
            
            if(pro.cumpleMes()){
                float Sueldo,Resultado;
                Sueldo = pro.getSueldo();
                
                Resultado = Sueldo + Sueldo * pro.getSueldoExtra();
                
                jTFSueldo.setText(Float.toString(Resultado));
            }else
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "Error. El Empleado no cumple el requisito de 1 mes mínimo");
            }
        }
    }//GEN-LAST:event_BotCalcularActionPerformed
   
    public void disableText(){
        jTFNombre.setEditable(false);
        jTFFecha.setEditable(false);
        jTFSueldo.setEditable(false);
    }
    
    public void setJTextField(Lista <Empleado> p){
        String cadena = p.extraerObjeto().toString();     
        String [] datos = cadena.split("\\*");
        jTextTipo.setText(datos[0]);
        jTextNumero.setText(datos[1]);
        jTFNombre.setText(datos[2]);
        jTFSueldo.setText(datos[3]);
        jTFFecha.setText(datos[4]);
        jTextPagas.setText(datos[5]);
        jTextAtributo.setText(datos[6]);

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAvanzar;
    private javax.swing.JButton BotCalcular;
    private javax.swing.JButton BotRetroceder;
    private javax.swing.JLabel jLabelAtributos;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPagas;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFSueldo;
    private javax.swing.JTextField jTextAtributo;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPagas;
    private javax.swing.JTextField jTextTipo;
    // End of variables declaration//GEN-END:variables

}
