package vista;
import Controlador.Lista;
import Controlador.Nodo;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import modelo.Empleado;

/**
 *
 * @author alumno
 */
public class PanelJLista extends javax.swing.JPanel {
    
    private Lista <Empleado> list;

    /**
     * Creates new form PanelJLista
     */
    public PanelJLista() {
        initComponents();
    }
    
    public void actualizaLista(Lista <Empleado> lista){
        this.list=lista;
    }
    
    public void iniciarJList(){
        if(list.vacia()){
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"AVISO. No hay ningún jugador registrado.");
        }
    }
    
    private DefaultListModel modeloLista()
    {
        //System.out.println("Entra en modeloLista");
        
        DefaultListModel<Empleado> modelo = new DefaultListModel<Empleado>();
        
        //System.out.println("Creado modelo");
        
        for(Nodo <Empleado> aux = list.primero(); aux != null; aux = aux.getSgt())
        {
            //System.out.println("Dentro del for");
            modelo.addElement(aux.getDato());
            //System.out.println("Modelo añadido");
        }
        
        //System.out.println("Va a salir");
        return modelo;
    }
    
    public void rellenaJList()
    {
        jList1.setModel(modeloLista());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        BotonMostrar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JList");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        BotonMostrar.setText("Mostrar");
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(BotonMostrar)))
                        .addGap(0, 166, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonMostrar)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        String men;
        Object jlist = jList1.getSelectedValue();
        
        if(jList1.getSelectedIndex() != -1)
        {
            men = "El elemento seleccionado es: \n" + jlist.toString();
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, men);
        }else
        {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "ERROR. No se ha seleccionado ningún elemento.");
        }
    }//GEN-LAST:event_BotonMostrarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
